# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [47]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [49]:
A = np.arange(1, 16).reshape(3,5)

In [51]:
print ("Number of axes:",A.ndim)
print ("Shape:",A.shape)
print ("Size:",A.size)
print ("Datatype:",A.dtype)

Number of axes: 2
Shape: (3, 5)
Size: 15
Datatype: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [105]:
import numpy as np
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print("Matrix B:\n",B)
print("Matrix C:\n",C)

Matris B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matris C:
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [125]:
#elementwise subtraction
element_subtract = B - C
print("Elementwise Subtraction:\n", element_subtract)

#elementwise multiplication
element_multiply = (B * C)
print("Elementwise Multiplication:\n", element_multiply)

#matrix multiplication
matrix_multiply = B @ C
print("Matrix Multiplication:\n",matrix_multiply)

Elementwise Subtraction:
 [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
Elementwise Multiplication:
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
Matrix Multiplication:
 [[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [215]:
import numpy as np
B = np.arange(1, 10).reshape(3, 3)

# elementvise exp
A = np.exp(B)

# minimum value in matrix B
min_value = np.min(B)

# minimun value in each row, Matrix B
min_value_row_1 = np.min(B,axis=1)

# sum for all elements
sum_elements = np.sum(B)

# mean for all elements
mean_elements = np.mean(B)

# median for all elements
median_elements = np.median(B)

print(f"Matrix:\n",B)
print()
print(f"Matrix Exp:\n",A)
print()
print(f"Minimum value element:\n",min_value)
print()
print(f"Minium value in each row (axis):\n",min_value_row_1)
print()
print(f"Sum for all elements:\n",sum_elements)
print()
print(f"Mean for all elements:\n",mean_elements)
print()
print(f"Median for all elements:\n",median_elements)
print()


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix Exp:
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value element:
 1

Minium value in each row (axis):
 [1 4 7]

Sum for all elements:
 45

Mean for all elements:
 5.0

Median for all elements:
 5.0



### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [217]:
print(A)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [219]:
A[1]

array([ 54.59815003, 148.4131591 , 403.42879349])

**Answer:**

In [ ]:
You select one, or two, of the axis. In this case you select the second row (1) and only show that as a result. 
This is an effective way to slice information without altering the array.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [231]:
# create matrix
A = np.arange(1, 16).reshape(3,5)

for i in np.nditer(A):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [233]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
# Answer
First a matrix is created with 30 instances and shaped into a matrix with 5 rows, 6 columns.
The third axis (-1) means as many columns as needed are created.

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [11]:
import numpy as np
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [7]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [9]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [71]:
# 10.1.1
import numpy as np
x=np.array([4,3])
x

#a What dimension has the vector x

# a  
# vector dimension is 1x2
print ("Vector:")
print (x)
print ()

#b Calculate 5x
print ("5x")
print (x*5)
print ()

#c Calculate 3x
print ("3x")
print (x*3)
print ()

#d Calculate 5x+3x
print ("5x + 3x")
print (x*(5+3))
print ()

#e Calculate 8x
print ("8x")
print (x*8)
print ()

#f Calulate 4x - x
print ("4x - x")
print ((x*4)-x)
print ()

# Calculate XT. What is the dimension after the tranposition
xt=np.transpose(x)
print ("Transposed vector")
print (xt)
print ()


Vector:
[4 3]

5x
[20 15]

3x
[12  9]

5x + 3x
[32 24]

8x
[32 24]

4x - x
[12  9]

Transposed vector
[4 3]



In [133]:
# 10.1.2
import numpy as np
v=np.array([3,7,0,11]).reshape(-1,1)
print ("Column vector:")
print (v)
print ()
#a What dimension has the vector?
# The dimension is 4x1

#b Calculate 2v
print ("2v")
print (2*v)
print ()

#c Calculate 5v + 2v
print ("5v + 2v")
print (v*(5+2))
print ()

#d Calculate 4v - 2v
print ("4v - 2v")
print (v*(4-2))
print ()

#e Calculate V|T
vt=np.transpose(v)
print ("Transposed v")
print (vt)
print ("New dimension is 1x4")
print ()

#f Calculate ||v||
print ("||v||" (Norm of V))
v_norm=np.linalg.norm(v)
print (v_norm)
print ()

Column vector:
[[ 3]
 [ 7]
 [ 0]
 [11]]

2v
[[ 6]
 [14]
 [ 0]
 [22]]

5v + 2v
[[21]
 [49]
 [ 0]
 [77]]

4v - 2v
[[ 6]
 [14]
 [ 0]
 [22]]

Transposed v
[[ 3  7  0 11]]
New dimension is 1x4

||v||
13.379088160259652



### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [30]:
# 10.1.3
import numpy as np
v1 = np.array([4,3,1,5])
v2 = np.array([2,3,1,1])

#a Calculate ||v1||
v1_norm = np.linalg.norm(v1)
v2_norm = np.linalg.norm(v2)
v_difference = v1-v2
v_res = np.linalg.norm(v_difference)

print ("||v1||")
print (v1_norm)
print("||v1-v2||")
print (v_res)
print ()

||v1||
7.14142842854285
||v1-v2||
4.47213595499958



### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [32]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [38]:
# If you change the last element in v2 the last element in v1 will also be changed. 
# This is because v2 is a view of v1 and share the same data buffer. Basic indexing creates views.

# Change the last element in v2 
v2[-1] = 5

print ("After change:") 
print ("v1:", v1) 
print ("v2:", v2)
print ()

After change:
v1: [0 1 2 5]
v2: [2 5]



In [40]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 5]


In [26]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[4 3 1 5]
[  2   3   1 123]
